### ISSUE TITLE
Cannot deploy to localstack

### ISSUE THREAD

**Issue by JacksonToomey** [localstack/serverless-localstack#101]
I am receiving an error trying to deploy to localstack:
```
2020-08-24T16:05:54:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource ApiGateway::Resource: 'ParentId' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 785, in retrieve_resource_details
localstack_main |     parent_id = resolve_refs_recursively(stack_name, resource_props['ParentId'], resources)
localstack_main | KeyError: 'ParentId'
```
This is followed by 
```
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 271, in parse_and_update_resource
localstack_main |     return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name, update=True)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 312, in _parse_and_create_resource
localstack_main |     parse_and_update_resource_orig(logical_id, resource_json_arns_fixed, resources_map, region_name)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 321, in parse_and_update_resource
localstack_main |     new_resource.type = resource_json["Type"]
localstack_main | AttributeError: 'NoneType' object has no attribute 'type'
localstack_main | 
```

**Comment by whummer** [comment]
Hi @JacksonToomey , thanks for reporting. Can you please provide a small (minimal) example of your `serverless.yml` configuration, to help us reproduce this issue? Thanks!

**Comment by JacksonToomey** [comment]
I'm using docker-compose to run localstack
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

My truncated serverless config is 
```
provider:
  name: aws
  stage: ${self:custom.derived.stage}
  runtime: python3.6
  timeout: 20
  region: us-east-1
  environment:
    ...
  apiKeys:
    - ${self:service}-${self:custom.derived.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "*"

functions:
  identify-handler:
    handler: lambdas.identify.handler
    events:
      - http:
          path: identify
          method: post
          private: true
  retrieve-handler:
    handler: lambdas.retrieve.handler
    events:
      - http:
          path: retrieve
          method: get
          private: true
  archive-handler:
    handler: lambdas.archive.handler
    events:
      - http:
          path: archive
          method: post
          private: true
  ingest-handler:
    handler: lambdas.ingest.handler
    events:
      - http:
          path: ingest
          method: post
          private: true
      - http:
          path: ingest
          method: get
          private: true
  ingest-priority-handler:
    handler: lambdas.ingest.handler
    events:
      - http:
          path: ingest-priority
          method: post
          private: true
      - http:
          path: ingest-priority
          method: get
          private: true
  status-handler:
    handler: lambdas.status.handler
    events:
      - http:
          path: status
          method: get
          private: true
  sftest:
    handler: lambdas.sftest.handler


plugins:
  - serverless-localstack
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-offline
  - serverless-step-functions
  - serverless-sam

package:
  include:
    - client/**
    - lambdas/**
  exclude:
    - ./**

stepFunctions:
  stateMachines:
    test:
      name: ${self:service}-${self:custom.derived.stage}-test
      definition:
        Comment: "Test"
        StartAt: First
        States:
          First:
            Type: Pass
            Result: "Output"
            Next: LambdaTask
          LambdaTask:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:custom.derived.stage}-sftest
            Next: Second
          Second:
            Type: Pass
            Result: "Final"
            End: true

custom:
  localstack:
    stages:
      - local
    lambda:
      mountCode: false
  pythonRequirements:
    usePoetry: false
    useDownloadCache: false
    useStaticCache: false
    pipCmdExtraArgs:
      - --no-cache
      - - --extra-index-url ...
  defaults:
    stage: local
    node_env: local
    region: us-east-1
    org_name: ...
  derived:
    stage: ${opt:stage, self:custom.defaults.stage}
    org_name: ${opt:org_name, self:custom.defaults.org_name}
    jfrog_credentials: ${env:JFROG_CREDENTIALS, ssm:/jfrog/credentials/build}
```
