### ISSUE TITLE
 The serverless deployment bucket "temp1-local-serverlessdeploymentbucket-rw8ijadcxsrd" does not exist.

### ISSUE THREAD

**Issue by yonahforst** [localstack/serverless-localstack#105]
Can't deploy to the latest version of localstack (images `c2ab68888913` and `bde78caedc06`). The last image that I CAN deploy to is `4395da9b0120`.

**serverless.yml**
```yml
service: temp1

custom:
  defaultStage: local
  stage: ${opt:stage, self:custom.defaultStage}
  localstack:
    host: http://${env:LOCALSTACK_HOST, 'localhost'}
    stages:
      - local

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${self:custom.stage}

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-localstack  
```

**docker-compose.yml**
```yml

version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "${EDGE_PORT-4566}:${EDGE_PORT-4566}"
    environment:
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - USE_LIGHT_IMAGE=1
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**docker logs**
```
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id temp1-local does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource temp1-local/ServerlessDeploymentBucket: None
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}}}
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region eu-west-1: create_bucket {'Bucket': 'ServerlessDeploymentBucket', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'eu-west-1'}}
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource temp1-local/ServerlessDeploymentBucketPolicy: None
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::BucketPolicy', 'Properties': {'Bucket': 'temp1-local-serverlessdeploymentbucket-yw5dnojh661b', 'PolicyDocument': {'Statement': [{'Action': 's3:*', 'Effect': 'Deny', 'Principal': '*', 'Resource': ['arn:aws:s3:::temp1-local-serverlessdeploymentbucket-yw5dnojh661b/*'], 'Condition': {'Bool': {'aws:SecureTransport': False}}}]}}}
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::BucketPolicy" id "ServerlessDeploymentBucketPolicy"
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::BucketPolicy" in region eu-west-1: put_bucket_policy {'Bucket': 'temp1-local-serverlessdeploymentbucket-yw5dnojh661b', 'Policy': '{"Statement": [{"Action": "s3:*", "Effect": "Deny", "Principal": "*", "Resource": ["arn:aws:s3:::temp1-local-serverlessdeploymentbucket-yw5dnojh661b/*"], "Condition": {"Bool": {"aws:SecureTransport": false}}}]}'}
localstack_1  | 2020-09-04T09:29:29:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'localstack.services.cloudformation.service_models.S3BucketPolicy'>
localstack_1  | 2020-09-04T09:29:29:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
```

**sls logs**
``` 
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Using serverless-localstack
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.135s 0 retries] describeStacks({ StackName: 'temp1-local' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.272s 0 retries] createStack({
  StackName: 'temp1-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.489s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-west-1:000000000000:stack/temp1-local/d409d892-5626-4a5d-910a-169d3e8580e4'
})
.
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.359s 0 retries] describeStackResource({
  StackName: 'temp1-local',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 404 0.423s 0 retries] listObjectsV2({
  Bucket: 'temp1-local-serverlessdeploymentbucket-yw5dnojh661b',
  Prefix: 'serverless/temp1/local'
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The serverless deployment bucket "temp1-local-serverlessdeploymentbucket-yw5dnojh661b" does not exist. Create it manually if you want to reuse the CloudFormation stack "temp1-local", or delete the stack if it is no longer required.
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:56:11
  From previous event:
      at AwsDeploy.getMostRecentObjects (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:50:13)
  From previous event:
      at AwsDeploy.checkForChanges (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:20:8)
  From previous event:
```
