### ISSUE TITLE
I Can’t get supersecret variables

### ISSUE THREAD

**Issue by danielcastill0** [localstack/serverless-localstack#106]
Hey guys I’m trying to put into my lambda function environment variables from SSM but I got something like “could be found the resource ...” when I did deploy. I already created my own secrets manager in localstack
But they aren’t recognized in my Serverless project. Can anyone help me?

**Comment by josephnle** [comment]
I think I'm also having an issue similar to this.

My project has a collection of serverless projects to split up the stack. I rely on CloudFormation outputs and SSM to share variables between the modules. It seems that I'm not able to reference outputs on locally created stacks.

For example, stack A:
```
service: notifications

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'local'}

custom:
  localstack:
    stages:
      - local
    autostart: true

resources:
  Resources:
    ArtifactChanges:
      Type: AWS::SNS::Topic

  Outputs:
    ArtifactChanges:
      Value: !Ref ArtifactChanges
```

Referenced in stack B:

```
service: api

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  profile: localstack
  environment:
    ARTIFACT_TOPIC: ${cf:notifications-${self:provider.stage}.ArtifactChanges}
```

Throws error:
```
Stack with id notifications-local does not exist
```

Is serverless-localstack not able to intercept the fetching of the SSM and CF output variables?

**Comment by whummer** [comment]
Thanks for reporting @danielcastill0 . Can you please share a small example to help us reproduce this issue? Generally speaking, referencing SSM parameters in your Serverless config should work - please make sure that the LocalStack region (via `DEFAULT_REGION`) matches the region of your sls stack. Thanks

Thanks for reporting @josephnle . Looks like your stack B may be talking to actual AWS, instead of LocalStack? I was actually able to get your example deployed by adding this section to serverless.yml for stack B:
```
custom:
  localstack:
    stages:
      - local
```
