### ISSUE TITLE
Reference CF Outputs throws "security token invalid"

### ISSUE THREAD

**Issue by Kesin1** [localstack/serverless-localstack#111]
I create a S3 Bucket with the following serverless.yml

```
service: s3-resource

frameworkVersion: "2"
plugins:
  - serverless-localstack

custom:
  defaultStage: local
  profiles:
    local: localstackProfile
    dev: serverlessMlProfile
  localstack:
    host: http://localhost	# http://${env:LOCAL_STACK_HOST} - optional - LocalStack host to connect to
    stages:
      - local
  stages:			#  stages in total.
    - local
    - dev
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: ${opt:stage, 'local'}	# i.e. serverless deploy --stage staging
  region: eu-west-3
  profile: ${self:custom.profiles.${opt:stage, self:provider.stage, 'local'}}
  
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket

  # Print out the name of the bucket that is created
  Outputs:
    BucketArn:
      Value:
         Fn::GetAtt:
          - S3Bucket
          - Arn
      Export:
        Name: ${self:custom.stage}-BucketArn

    BucketName:
      Value:
        Ref: S3Bucket
      Export:
        Name: ${self:custom.stage}-BucketName
```

and then I try to cross-stack reference the BucketName and BucketArn in my test_service (serverless.yml):
```
service: s3-test-service

frameworkVersion: "2"
plugins:
  - serverless-localstack

custom:
  defaultStage: local
  profiles:
    local: localstackProfile
    dev: serverlessMlProfile
  localstack:
    host: http://localhost	# http://${env:LOCAL_STACK_HOST} - optional - LocalStack host to connect to
    stages:
      - local
  stages:			#  stages in total.
    - local
    - dev
  stage: ${opt:stage, self:provider.stage}
    
provider:
  name: aws
  stage: ${opt:stage, 'local'}	# i.e. serverless deploy --stage staging
  region: eu-west-3
  profile: ${self:custom.profiles.${opt:stage, self:provider.stage, 'local'}}  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: ${cf:s3-resource-${self:custom.stage}.BucketArn}


functions:
  s3_handler:
    handler: handler.handler
    runtime: python3.8 # optional overwrite, default is provider runtime
    events:
      - s3:
          bucket: {'Fn::ImportValue': '${self:custom.stage}-BucketName'}
          existing: true
```

This is my dokcer-compose.yml:
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4513:4513"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=...
      - DEFAULT_REGION=eu-west-3
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

My Credentials are set to none
```
[localstackProfile]
aws_access_key_id=None
aws_secret_access_key=None
```

Deploying to Localstack throws the error:
"The security token included in the request is invalid."

But it works fine deploying it directly to AWS

(The same problem arises when cross-referencing layers and also using the syntax
```${cf:s3-resource-${self:custom.stage}.BucketName}```
