### ISSUE TITLE
serverless-localstack not able to use dummy aws config when interacting with ECR

### ISSUE THREAD

**Issue by alexbussan** [localstack/serverless-localstack#135]
when I run `serverless deploy -s local -v --profile localstack` I get: 

`The security token included in the request is invalid.` under the Serverless Error output. 
I have this in my credentials:
```
[localstack]
aws_access_key_id = foo
aws_secret_access_key = bar
```

localstack.yml:
```
version: '3.8'
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"
      - "4566:4566"
      - "443:443"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,sts,cloudformation,s3,iam,lambda,apigateway,serverless,ecr
      - LAMBDA_EXECUTOR=docker-reuse
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=XXX
      - AWS_SECRET_ACCESS_KEY=XXX
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 ```

simplified serverless.yml:
```
service: purple
frameworkVersion: 2

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

provider:
  name: aws
  profile: localstack
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      helloimage:
        path: ./
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    image:
      name: helloimage
```

If i take out the ECR parts like so, `serverless deploy -s local -v --profile localstack` works fine:
```
service: purple
frameworkVersion: 2

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

provider:
  name: aws
  profile: localstack
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handler.hello
```

Any ideas? Not sure why interacting with ECR would affect this
