### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ccmattr** [localstack/serverless-localstack#149]
I'm having trouble getting a basic code example up and running because of a weird error. Where am I going wrong here?

Serverless.yml:

```
service: example
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-step-functions
  - serverless-localstack
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: index.handler

stepFunctions:
  stateMachines:
    example:
      name: Example
      definition:
        Comment: Hello World
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource: 
              Fn::GetAtt: [hello, Arn]
            End: true


custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: 
      forceExclude:
        - aws-sdk
    keepOutputDirectory: true
    excludeFiles: "**/*.test.js"

  localstack:
    stages:
      - local
    autostart: true  # optional - Start LocalStack in Docker on Serverless deploy
    lambda:
      mountCode: true
```

Output from deploy:

```
❯ SLS_DEBUG=* sls deploy --stage local -v
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command invoke
Serverless: Load command invoke:stepf
Serverless: Using serverless-localstack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessStepFunctions for "name", "data", "path", "stage", "region"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Using configuration:
{
  "webpackConfig": "webpack.config.js",
  "includeModules": {
    "forceExclude": [
      "aws-sdk"
    ]
  },
  "keepOutputDirectory": true,
  "excludeFiles": "**/*.test.js",
  "packager": "npm",
  "packagerOptions": {},
  "concurrency": 8
}
Serverless: Removing /home/matt/source/example/.webpack
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
1 asset
4 modules
webpack 5.38.1 compiled successfully in 160 ms
Serverless: Invoke webpack:package
Serverless: Fetch dependency graph from /home/matt/source/example/package.json
Serverless: No external modules needed
Serverless: Zip method used: node
Serverless: Zip service: /home/matt/source/example/.webpack/service [49 ms]
Serverless: Copying existing artifacts...
Serverless: Setting artifact for function 'hello' to '.serverless/example.zip'
Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
Serverless: Skip plugin function ServerlessWebpack.cleanup (lambda.mountCode flag is enabled)
Serverless: Skip plugin function AwsCompileFunctions.downloadPackageArtifacts (lambda.mountCode flag is enabled)
Serverless: Invoke aws:package:finalize
AWS Pseudo Parameters
Skipping automatic replacement of regions with account region!
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Skip plugin function AwsDeploy.uploadFunctionsAndLayers (lambda.mountCode flag is enabled)
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - Example
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - HelloLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - ExampleRole
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - Example
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - example-local
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: example
stage: local
region: us-east-1
stack: example-local
resources: 8
api keys:
  None
endpoints:
  None
functions:
  hello: example-local-hello
layers:
  None

Stack Outputs
ServerlessDeploymentBucketName: example-local-serverlessdeploymentbucket-9639a47d
HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:000000000000:function:example-local-hello:$LATEST:$LATEST
ExampleArn: arn:aws:states:us-east-1:000000000000:stateMachine:Example


 Type Error ----------------------------------------------

  TypeError: Cannot read property 'replace' of undefined
      at ServerlessStepFunctions.newDisplay [as display] (/home/matt/source/example/node_modules/serverless-localstack/src/index.js:661:47)
      at ServerlessStepFunctions.tryCatcher (/home/matt/source/example/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/matt/source/example/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/matt/source/example/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/matt/source/example/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/matt/source/example/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:462:21)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.0
     Framework Version:         2.44.0
     Plugin Version:            5.2.0
     SDK Version:               4.2.3
     Components Version:        3.11.0

```

Invoke output:

```
❯ sls invoke stepf -s local -n example -d hello
Serverless: Using serverless-localstack
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessStepFunctions for "name", "data", "path", "stage", "region"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

 Type Error ----------------------------------------------

  TypeError: Cannot read property 'replace' of undefined
      at Object.getNormalizedResourceName (/home/matt/.npm-global/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:584:44)
      at Object.getNormalizedFunctionName (/home/matt/.npm-global/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:134:17)
      at ServerlessStepFunctions.getStateMachineOutputLogicalId (/home/matt/source/example/node_modules/serverless-step-functions/lib/naming.js:23:8)
      at ServerlessStepFunctions.getStateMachineArn (/home/matt/source/example/node_modules/serverless-step-functions/lib/invoke/invoke.js:8:40)
      at ServerlessStepFunctions.tryCatcher (/home/matt/source/example/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/matt/source/example/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/matt/source/example/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/matt/source/example/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/matt/source/example/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/matt/source/example/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:462:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.0
     Framework Version:         2.44.0
     Plugin Version:            5.2.0
     SDK Version:               4.2.3
     Components Version:        3.11.0

```

**Comment by fsmawi** [comment]
Hi, I'm facing the same issue, trying to deploy a stack including step functions to localstack:
```
...
layers:
  None
 
 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'replace' of undefined
      at ServerlessStepFunctions.newDisplay [as display] (/app/node_modules/serverless-localstack/src/index.js:661:47)
      at ServerlessStepFunctions.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.1
     Framework Version:         2.48.0 (local)
     Plugin Version:            5.4.2
     SDK Version:               4.2.3
     Components Version:        3.12.0
...
```

**Comment by fsmawi** [comment]
for anybody who is interested, we found a workaround. It seems that the step-functions plugin expects the service endpoint to be returned in the output of the stack deployment. So just adding the following lines will work:
```
resources:
  Outputs:
    ServiceEndpoint:
      Description: the custom service endpoint
      Value: ${self:custom.servicesEndpoint}
```

**Comment by Hobbit44** [comment]
@fsmawi what have you got `custom.servicesEndpoint` defined as?

**Comment by fsmawi** [comment]
you can add any value there @Hobbit44
```
resources:
  Outputs:
    ServiceEndpoint:
      Description: the custom service endpoint
      Value: http://localstack:4566
```
