### ISSUE TITLE
Type Error when attempting to deploy to local stack.

### ISSUE THREAD

**Issue by jwanga** [localstack/serverless-localstack#15]
I get the following when attempting to deploy to localstack. The only odd thing I can think of is that I'm running babel to transpile my files into a .bin directory and that's where I'm pointing my handlers.

My serverless.yaml looks like this:

```
service: api-cloud-functions 

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
  region: us-east-1

functions:
  console-auth:
    handler: handler.consoleAuth
plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568

```

The deploy output looks like this:

```
Serverless: Using serverless-localstack
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 4 of 4
 
  Type Error ---------------------------------------------
 
  e.message.indexOf is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           11.11.0
     Serverless Version:     1.39.1
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leialoft-api-cloud-functions@1.0.0 deploy: `serverless deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api-cloud-functions@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Localstack is printing the following when I attempt to deploy:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/user.name/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/user.name/Library/Python/3.7/lib/python/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10fb61eb8>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

Im unsure how to proceed. Thanks!

**Comment by nub340** [comment]
I get the same error when I start localstack directly in a terminal window and then attempt to serverless deploy to it. 

However, when I start localstack in a docker container and then try to serverless deploy to it, I get a different error (see below).  

My serverless.yml looks like so:

```
service: api-gateway

provider:
  name: aws  
  runtime: nodejs8.10
  region: us-east-1
  stage: local

functions:
  apiGateway:
    handler: src/gateway/gateway.handler
    name: apiGateway
    events:
      - http:
          path: gateway
          method: get
      - http:
          path: gateway
          method: post
  testMicroservice:
    handler: src/test-microservice/test-microservice.handler
    name: testMicroservice
    events:
      - http:
          path: test-microservice
          method: get
      - http:
          path: test-microservice
          method: post

package:
  individually: true
  
plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  localstack:
    host: http://localhost
    stages:
      - dev
      - local
    autostart: true
    lambda:
      mountCode: True
  stages:
    dev:
```
I am unsure about that last part end of the yml. The localstack docs show "..." under dev: but it's not clear to me what exactly goes there or if it's required. Anyhow, I'm on Mac so I open a new terminal window and run localstack like so:

`TMPDIR=/private$TMPDIR SERVICES=\"lambda,s3,cloudwatch,cloudformation,sts\" localstack start --docker`

This starts up localstack with only the specified services running in a docker container. Since I don't need any of the other services this helps speed things up a bit.

Then I attempt to deploy to localstack by running:

`SLS_DEBUG=* serverless --stage local deploy`

At this point a whole lot of stuff happens and it seems like it's going to work and then I get lots of python errors in the localstack terminal like so:

`2019-03-19T23:52:08:WARNING:localstack.services.awslambda.lambda_api: Unknown error: Command'ls -la /Users/nub340/code/gateway' returned non-zero exit status 1 Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 629, in create_function
result = set_function_code(data['Code'], lambda_name)
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 517, in set_function_code
file_list = run('ls -la %s' % lambda_cwd)
File "/opt/code/localstack/localstack/utils/common.py", line 847, in run
return do_run(cmd)
File "/opt/code/localstack/localstack/utils/common.py", line 844, in do_run
raise e
CalledProcessError: Command 'ls -la /Users/nub340/code/gateway' returned non-zero exit status 1`

and then the serverless deploy finally fails with:

```
...
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 500 33.473s 3 retries] updateStack({ StackName: 'api-gateway-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL:
   'https://s3.amazonaws.com/api-gateway-local-ServerlessDeploymentBucket-298418A-Z24A-Z07/serverless/api-gateway/local/1553038530020-2019-03-19T23:35:30.020Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })

  Serverless Error ---------------------------------------

  500

  Stack Trace --------------------------------------------

ServerlessError: 500
    at promise.catch.err (/Users/nub340/.nvm/versions/node/v11.7.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:295:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Note that when I simply run `serverless start`, everything works fine and I can invoke my lambda functions via HTTP requests from Postman no problemo. I'm sure I'm doing something wrong here but it's not clear to me what or how I should proceed. What's up with that last "dev:" node in the yml, am I missing something there?? Any help would be appreciated.
