### ISSUE TITLE
Deploying to aws rather than Localstack when config is in a referenced file

### ISSUE THREAD

**Issue by matt-jenner** [localstack/serverless-localstack#16]
### Bug Report

**What went wrong:**
When referencing the `custom:` section of serverless.yml from a separate config file, serverless-localstack did not redirect properly and it deployed to real aws.

As soon as I switched from providing my config within serverless.yml like so:

```
custom:
  app_name: "serverless-localstack-bug"
  stage: ${opt:stage, 'dev'}

  localstack: 
    host: http://localhost
    stages:
      # list of stages for which the plugin should be enabled
      - local
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
    lambda:
      # Enable this flag to improve performance
      mountCode: True
```

to referencing a file using:

`custom: ${file(./config/serverless.${opt:stage, 'dev'}.config.yml):custom}`

which contains the exact same code, the problem started.

**Expected Outcome:**
Before the plugin starts, it reads the whole processed serverless file and acts as it did when the custom section was part of the main serverless.yml file.  A deployment to localstack and no interaction with real AWS.

**Actual Outcome:**
S3 bucket created and cloudformation template uploaded, but failed as the template was invalid.

it seems to ignore the config and create the S3 bucket on AWS instead which then fails to deploy properly with the following error:

```
  Error --------------------------------------------------

  The CloudFormation template is invalid: Invalid template resource property 'Subscription'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: The CloudFormation template is invalid: Invalid template resource property 'Subscription'
    at provider.request.catch (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:24:13)
From previous event:
    at AwsDeploy.validateTemplate (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:10)
    at BbPromise.reduce (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at AwsDeploy.BbPromise.bind.then (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:10)
    at BbPromise.reduce (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.run (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:438:17)
    at variables.populateService.then.then (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/bin/serverless:43:28)
    at /home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:139:20)
From previous event:
    at initializeErrorReporter.then (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at /home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/mjenner/.nvm/versions/node/v10.9.0/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
````

**Notes**

I've successfully used serverless-localstack to deploy locally, but as I come to extend my code to containerize it, I need to create a separate stage and config forcontainerised running to point serverless at the containerized endpoint names (http://localhost --> http://localstack).

I'm not quite sure if the bug lies within how the plugin reads the config or how serverless prepares the final version of the serverless configuration before starting the plugins but any help would be greatly appreciated as this is blocking my integration test efforts in CI, thanks in advance.
