### ISSUE TITLE
Cannot get SecretsManger param using ssm:/aws/reference/secretsmanager

### ISSUE THREAD

**Issue by tudor2004** [localstack/serverless-localstack#164]
I am creating the ssm param before running "serverless deploy" using the following command `docker run --rm -e AWS_ACCESS_KEY_ID=foobar -e AWS_SECRET_ACCESS_KEY=foobar --network=backend -it amazon/aws-cli secretsmanager --endpoint-url=http://localstack:4566 --region=us-east-1 create-secret --name lambda_secret --secret-string "mySecret"`

The secret gets created successfully and I can also see it in the localstack dashboard. 

After it is created, I am running the `serverless deploy --stage=local` command for the following template:

```
service: localstack-lambda
frameworkVersion: "2"
plugins:
  - serverless-localstack

custom:
  secret: ${ssm:/aws/reference/secretsmanager/lambda_secret}
  localstack:
    debug: true
    stages: [local]

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  individually: true

functions:
  my-lambda-fn:
    handler: index.handler
    description: Some lambda function
    package:
      patterns:
        - "!**"
        - index.js
        - package.json
        - node_modules/**
```

But when running `serverless deploy --stage locale` I get the following output:

```
 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/aws/reference/secretsmanager/lambda_secret' could not be found.
```

**Comment by jeffgunderson** [comment]
Make sure the `ssm` service is running in localstack as well as secretsmanager. 

```
environment:
      - SERVICES=secretsmanager,ssm
```

Also in your example you're passing "locale" as the stage but should be "local" based on your serverless.yml.

**Comment by henriqueleite42** [comment]
I'm also having the same issue, but my `serverless.yml` has some differences:

```yml
# Because of https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store
variablesResolutionMode: "20210326"

custom:
  # I tried both ways, this way:
  secret: ${ssm:/aws/reference/secretsmanager/lambda_secret}
  # And this way:
  secret: ${ssm:lambda_secret}
```

And the error that I'm getting is:
```txt
Serverless: Using serverless-localstack

Serverless Error ----------------------------------------

 Cannot resolve serverless.ts: Variables resolution errored with:
   - Cannot resolve variable at "custom.secret": ,

 Get Support --------------------------------------------
    Docs:          docs.serverless.com
    Bugs:          github.com/serverless/serverless/issues
    Issues:        forum.serverless.com

 Your Environment Information ---------------------------
    Operating System:          linux
    Node Version:              14.18.1
    Framework Version:         2.68.0 (local)
    Plugin Version:            5.5.1
    SDK Version:               4.3.0
    Components Version:        3.18.1
```
