### ISSUE TITLE
Getting TypeError while trying to deploy a Serverless framework Python lambda with mountCode: true

### ISSUE THREAD

**Issue by srinivaskalyani** [localstack/serverless-localstack#174]
I followed the instructions provided in [the official documentation](https://docs.localstack.cloud/tools/lambda-tools/hot-swapping/#serverless-framework-configuration) to execute a custom Python lambda using the Serverless framework. I am using the following command to deploy the lambda from the `my_serverless_root` directory:
```bash
LAMBDA_MOUNT_CWD=$(pwd)/build/hot serverless deploy --stage local
```
Following is my `serverless.yml` : 

```yaml
service: thetenant-service
plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-localstack

custom:
  pythonRequirements:
    dockerizePip: false
  localstack:
    stages:
      - local
    debug: true
    host: http://localhost
    edgePort: 4566
    region: us-east-1
    lambda:
      mountCode: true

package:
  exclude:
    - ./**
  include:
    - my_serverless_root/**

provider:  
  name: aws
  runstime: python3.7
  stage: ${opt:stage, 'default_stage'}
  tenant: thetenant
  region: us-east-1
  deploymentBucket: my-deployment-bucket
  role: arn:aws:iam::#{AWS::AccountId}:role/MyLambdaExecutionRole
  environment:
    STAGE: ${self:provider.stage}
    TENANT: ${self:provider.tenant}

functions:
  my_function:
    name: ${self:provider.tenant}-my-function
    handler: my_handler_dir.aws.my_handler_file.handler
    events:
      - http: POST /my_api/endpoint
```
I am getting the following error while trying to deploy:
```javascript
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
      at readFile (node:fs:393:10)
      at go$readFile (/home/srinivas/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:118:14)
      at readFile (/home/srinivas/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:115:12)
      at go$readFile (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/graceful-fs/graceful-fs.js:118:14)
      at Object.readFile (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/graceful-fs/graceful-fs.js:115:12)
      at Object.readFile (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/serverless-python-requirements/node_modules/universalify/index.js:5:57)
      at Object.tryCatcher (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/util.js:16:23)
      at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
      at injectRequirements (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/serverless-python-requirements/lib/inject.js:27:6)
      at ServerlessPythonRequirements.injectAllRequirements (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/serverless-python-requirements/lib/inject.js:149:13)
      at ServerlessPythonRequirements.<anonymous> (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/serverless-python-requirements/index.js:218:43)
      at ServerlessPythonRequirements.tryCatcher (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/srinivas/work/my_root_dir/integrations/my_serverless_root/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:464:21)

```
The same error occurs with both localstack cli as well as the standard non-customized `docker-compose.yml` file [provided here](https://github.com/localstack/localstack/blob/master/docker-compose.yml).
