### ISSUE TITLE
Golang taking minutes to run 

### ISSUE THREAD

**Issue by theprobugmaker** [localstack/serverless-localstack#181]
I created a hello world example using Golang and when I call the endpoint it takes up to 3/4 minutes to execute.

main.go:

```golang
package main

import (
	"fmt"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

func Handler(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	fmt.Println("Received body: ", request.Body)

	return events.APIGatewayProxyResponse{Body: request.Body, StatusCode: 200}, nil
}

func main() {
	lambda.Start(Handler)
}
```

serverless.yml:

```yml
service: go-serverless

provider:
  name: aws
  stage: local
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages: [local]

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: post
```

package.json:

```json
{
  "private": true,
  "name": "go-serverless",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "dependencies": {
    "serverless": "^3.7.1"
  },
  "devDependencies": {
    "serverless-localstack": "^0.4.35"
  }
}
```

What am I doing wrong? Thank you.
