### ISSUE TITLE
ssm parameter not found, issue starts in version 0.4.20

### ISSUE THREAD

**Issue by Psynbiotik** [localstack/serverless-localstack#190]
I have a config similar to this:

```
service: apps

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:ENVIRONMENT}
  timeout: 300
  memorySize: 256
  versionFunctions: false
  region: ${env:AWS_REGION}
  environment:
    ENVIRONMENT: ${env:ENVIRONMENT}
    MY_URL:${ssm:/path/to/entry}

custom:
  localstack:
    host: http://localhost
    edgePort: 4566
    endpoints:
       SSM: http://localhost:4566
    stages:
      - local

functions:
  example:
    handler: functions/example/index.handler

plugins:
  - serverless-localstack
```

In version 0.4.19 it will resolve the ssm value correctly, in version 0.4.20 it will not. I think it is related to this ticket: https://github.com/localstack/serverless-localstack/issues/53

The error is like this:
A valid SSM parameter to satisfy the declaration 'ssm:/path/to/entry' could not be found.
