### ISSUE TITLE
Unable to create S3 trigger with `existing: true` parameter

### ISSUE THREAD

**Issue by codeeno** [localstack/serverless-localstack#206]
Hello everyone!

I'm currently running into issues when trying to create a Lambda which uses an `s3:ObjectCreated:*` event from an existing S3 bucket as its trigger. While I am able to create the Lambda function itself, the S3 trigger does not seem to be added.

Localstack outputs the following warning:
```
2023-01-24T09:05:15.492  WARN --- [uncthread105] l.u.c.template_deployer    : Unable to deploy resource type "S3": {"Type": "Custom::S3", "Version": 1, "DependsOn": ["MyDashtestDashfunctionLambdaFunction", "CustomDashresourceDashexistingDashs3LambdaFunction"], "LogicalResourceId": "MyDashtestDashfunctionCustomS31", "Properties": {"ServiceToken": "arn:aws:lambda:us-east-1:000000000000:function:my-test-service-local-custom-resource-existing-s3", "FunctionName": "my-test-service-local-my-test-function", "BucketName": "my-test-bucket", "BucketConfigs": [{"Event": "s3:ObjectCreated:*", "Rules": [{"Prefix": "test/prefix"}, {"Suffix": ".txt"}]}]}}
```

I'm not sure if this is a bug or if I'm forgetting something.

## Steps to reproduce

1. Spin up localstack: `docker run --rm --name localstack --network="localstack-network" -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack`
2. Create an S3 bucket: `awslocal s3api create-bucket --bucket my-test-bucket --region us-east-1`
3. Create a `serverless.yaml` with the following content:
```yaml
service: my-test-service

provider:
  name: aws
  stage: development
  region: us-east-1

custom:
  localstack:
    stages:
      - local

plugins:
  - serverless-localstack

functions:
  my-test-function:
    memorySize: 128
    runtime: nodejs16.x
    timeout: 40
    handler: ./index.handler
    events:
      - s3:
          bucket: my-test-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: test/prefix
            - suffix: .txt
          existing: true
```
4. Create an `index.js` with the following content:
```javascript
module.exports.handler = (event) => {
  return true
}
```
5. Run `npm init --yes && npm i --save-dev serverless-offline`
6. Run `npx serverless deploy --stage local`
7. Run `awslocal s3api put-object --bucket my-test-bucket --key test/prefix/test.txt --body ./index.js`

The Lambda function does not get triggered. 

When doing the above setup without creating an S3 bucket and commenting out the `existing: true` line, the Lambda does get triggered when putting an object.

**Comment by asztal** [comment]
I had the same issue and ended up just defining the `NotificationConfiguration` myself for that bucket in the Resources section of serverless.yml. Of course, this only works if the bucket is defined in the same stack.

```
                BucketName: foo
                NotificationConfiguration:
                    LambdaConfigurations:
                        - Event: s3:ObjectCreated:*
                          Function: !GetAtt SomeLambdaFunction.Arn
```
