### ISSUE TITLE
Cannot resolve variable `${cf:}`

### ISSUE THREAD

**Issue by zoiman** [localstack/serverless-localstack#218]
When I try to reference variables from the cloudformation stack like this:

```
   iam:
     role:
       statements:
         - Effect: 'Allow'
           Action:
             - 'dynamodb:*'
           Resource:
             - ${cf:${self:custom.infrastructureStack}.TableArn}`
```

I receive the following error when deploying to localstack:
` - Cannot resolve variable at "provider.iam.role.statements.0.Resource.0": Value not found at "cf" source,`

The serverless containing this resource was successfully deployed before to localstack.

Deploying to AWS works.
