### ISSUE TITLE
Empty stage in API Gateway output for endpoints

### ISSUE THREAD

**Issue by hahuang65** [localstack/serverless-localstack#221]
With this `serverless.yml`:

```
service: scraperator
frameworkVersion: "3"
provider:
  name: aws
  runtime: python3.9
  stage: local
  region: us-east-1
  logs:
    httpApi: true
  deploymentBucket:
    name: serverless-deploys
    serverSideEncryption: AES256
  httpApi:
    cors: true
    disableDefaultEndpoint: false
plugins:
  - serverless-python-requirements
  - serverless-localstack
custom:
  stage: ${opt:stage, self:provider.stage}
  localstack:
    stages:
      - local
    autostart: false
functions:
  config:
    handler: capture.config
    events:
      - httpApi:
          method: GET
          path: /config
  capture:
    handler: capture.handler
    events:
      - httpApi:
          method: POST
          path: /capture
```

A successful deploy yields this output:

```
endpoints:
  GET - https://746fbc6e.execute-api.localhost.localstack.cloud:4566//config
  POST - https://746fbc6e.execute-api.localhost.localstack.cloud:4566//capture
```

Note the `//` where there should be `/local/`.
The URL as printed does not work. However, removing a `/` (e.g. https://746fbc6e.execute-api.localhost.localstack.cloud:4566/config) does work.
