### ISSUE TITLE
v1 API Gateway endpoints not getting printed out to the console

### ISSUE THREAD

**Issue by kristallizer** [localstack/serverless-localstack#230]
In `serverless.yml`:

```yml
functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /
          method: get

  upload-link:
    handler: src/functions/uploadLink.handler
    events:
      - http:
          path: /upload-link
          method: post

  download-file:
    handler: src/functions/downloadFile.handler
    events:
      - http:
          path: /download-file/{fileLinkUlid}
          method: get
```

When I deploy to AWS:

```shell
endpoints:
  GET - https://6a9876os1c.execute-api.us-east-1.amazonaws.com/k3/
  POST - https://6a9876os1c.execute-api.us-east-1.amazonaws.com/k3/upload-link
  GET - https://6a9876os1c.execute-api.us-east-1.amazonaws.com/k3/download-file/{fileLinkUlid}
functions:
  index: service-k3-index (55 MB)
  upload-link: service-k3-upload-link (55 MB)
  download-file: service-k3-download-file (55 MB)
```

When I deploy to the `local` stage using Localstack:

```shell
Deploying service to stage local (us-east-1)
Using serverless-localstack
Using serverless-localstack
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
Skip plugin function AwsCompileFunctions.downloadPackageArtifacts (lambda.mountCode flag is enabled)
Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Skipping template validation: Unsupported in Localstack

✔ Service deployed to stack service-local (21s)

endpoint: http://localhost:4566/restapis/tbwgi0iega/local/_user_request_
functions:
  index: service-local-index (31 kB)
  upload-link: service-local-upload-link (31 kB)
  download-file: service-local-download-file (31 kB)
```
