### ISSUE TITLE
Stuck on Need a faster logging experience when using serverless-stack with serverless-esbuild

### ISSUE THREAD

**Issue by keyvhinng** [localstack/serverless-localstack#248]
After running `serverless deploy`, the lambda is indeed deployed to `LocalStack` but the process is still running and stuck on:

```
Need a faster logging experience than CloudWatch? Try our Dev Mode in Console: run "serverless dev"
```

How to reproduce:

serverless.yml
```
service: serverless-localstack

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-esbuild
  - serverless-localstack

functions:
  hello:
    handler: handler.hello
```

handler.ts
```
export const hello = async (event) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: "Go Serverless",
      input: event,
    }),
  };
};

```
