### ISSUE TITLE
500 error from serverless on deployment

### ISSUE THREAD

**Issue by whummer** [localstack/serverless-localstack#3]
Copied from: https://github.com/localstack/localstack/issues/855 Koalk

- - -
Can't seem to create tickets on the new project, feel free to copy this into it once issues are enabled on it.
I am trying to deploy a local version of 2 lambdas plus a stepfunction, all quite basic stuff.
I get a 500 error from the serverless side of the deployment and quite the amount of logs in the localstack side. I'll put both here in case they are of any use.
[Localstack logs](https://pastebin.com/TvHgRZ38)
[Serverless logs](https://pastebin.com/68RYTsLE)
[serverless.yml](https://pastebin.com/RkABm2HB)

Is suppose to be a basic "lambda one loads new data somewhere and lambda two does some processing on it" with the step function as a glue between them and failover.

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-44) by [Unito](https://www.unito.io/learn-more)

**Comment by mpfeil** [comment]
I am getting the following 500 error when trying to deploy to localstack:
```
...
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.054s 0 retries] describeStacks({ StackName: 'myService-local' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 500 61.999s 3 retries] createStack({ StackName: 'myService-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody:
   '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 500 64.294s 3 retries] createStack({ StackName: 'myService-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody:
   '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 2 of 4
...
```

My `serverless.yml` looks like this:
```yaml
service: myService

provider:
  name: aws
  runtime: nodejs6.10
  memory: 128
  region: us-east-1

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost

functions:
  hello:
    handler: handler.hello
```

I have started `localstack` with docker-compose:
```yaml
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,cloudformation,iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

@whummer do you have any idea and can help me?
