### ISSUE TITLE
reconfigureAWS doesn't resolve env variables

### ISSUE THREAD

**Issue by tgrades** [localstack/serverless-localstack#53]
I'm getting `KeyError: '${env:AWS_REGION}'` error bc plugin doesn't resolve AWS_REGION env variable in serverless config.
When deploying to real aws it's resolved to `region: 'eu-west-1',` in config, but when I use localstack it stays `region: '${env:AWS_REGION}',`

**Comment by whummer** [comment]
Thanks for reporting @tgrades . Can you please share the relevant snippet of your Serverless config to make it easier to reproduce this issue? Thanks!

**Comment by tgrades** [comment]
Sure. Here:
```
service: apps

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:ENVIRONMENT}
  timeout: 300
  memorySize: 256
  versionFunctions: false
  region: ${env:AWS_REGION}
  environment:
    ENVIRONMENT: ${env:ENVIRONMENT}

custom:
  localstack:
    stages:
      - local

functions:
  example:
    handler: functions/example/index.handler

plugins:
  - serverless-localstack
```
