### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:4592

### ISSUE THREAD

**Issue by koper89** [localstack/serverless-localstack#59]
Hello,

Seems like I cannot force serverless-localstack to push my lambda towards localstack.

Here's serverless config:
```
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  timeout: 30
  environment:
    LAMBDA_REMOTE_DOCKER: true
functions:
  .......
plugins:
   - serverless-python-requirements
   - serverless-localstack
custom:
  pythonRequirements:
     dockerizePip: true
  localstack:
    host: http://localhost  # optional - LocalStack host to connect to
    debug: true
```
Docker Compose:
```  
version: "3"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb,kinesis,lambda,iam,apigateway,sns,cloudformation,serverless
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
```

Logs serverless:
```
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4569
Serverless: Reconfiguring service kinesis to use http://localhost:4568
Serverless: Reconfiguring service route53 to use http://localhost:4580
Serverless: Reconfiguring service firehose to use http://localhost:4573
Serverless: Reconfiguring service stepfunctions to use http://localhost:4585
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service sts to use http://localhost:4592
Serverless: Reconfiguring service iam to use http://localhost:4593
Serverless: Reconfiguring service ssm to use http://localhost:4583
Serverless: Reconfiguring service rds to use http://localhost:4594
Serverless: Reconfiguring service ec2 to use http://localhost:4597
Serverless: Reconfiguring service elasticache to use http://localhost:4598
Serverless: Reconfiguring service kms to use http://localhost:4599
Serverless: Reconfiguring service secretsmanager to use http://localhost:4584
Serverless: Reconfiguring service logs to use http://localhost:4586
Serverless: Reconfiguring service cloudwatchlogs to use http://localhost:4586
Serverless: Reconfiguring service iot to use http://localhost:4589
Serverless: Reconfiguring service cognito-idp to use http://localhost:4590
Serverless: Reconfiguring service cognito-identity to use http://localhost:4591
Serverless: Reconfiguring service ecs to use http://localhost:4601
Serverless: Reconfiguring service eks to use http://localhost:4602
Serverless: Reconfiguring service xray to use http://localhost:4603
Serverless: Reconfiguring service appsync to use http://localhost:4605
Serverless: Reconfiguring service cloudfront to use http://localhost:4606
Serverless: Reconfiguring service athena to use http://localhost:4607
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: config.options_stage: undefined
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: config.stage: dev
Serverless: Generated requirements from /.../requirements.txt in /.../.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /.../.cache/serverless-python-requirements/0b6046c3411ae9fc7ee5417b702696535b44420a56ff46a0d8d7a4fbdf03d488_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
Serverless: Recoverable error occurred (502), sleeping for ~5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (502), sleeping for ~6 seconds. Try 2 of 4
Serverless: Recoverable error occurred (502), sleeping for ~6 seconds. Try 3 of 4
Serverless: Recoverable error occurred (502), sleeping for ~6 seconds. Try 4 of 4
 
  Serverless Error ---------------------------------------
 
  502
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.17.0
     Framework Version:         1.59.3
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
Log docker-compose:
```
localstack    | 2019-12-10 08:07:00,408 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack    | 2019-12-10 08:07:00,411 INFO supervisord started with pid 13
localstack    | 2019-12-10 08:07:01,416 INFO spawned: 'dashboard' with pid 19
localstack    | 2019-12-10 08:07:01,419 INFO spawned: 'infra' with pid 20
localstack    | (. .venv/bin/activate; bin/localstack web)
localstack    | 2019-12-10 08:07:01,424 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack    | (. .venv/bin/activate; exec bin/localstack start --host)
localstack    | 2019-12-10 08:07:02,426 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack    | 2019-12-10T08:07:03:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
localstack    | 2019-12-10T08:07:03:INFO:localstack.utils.common: Unable to store certificate file under /tmp/localstack/server.test.pem, using tmp file instead: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'
localstack    | Starting local dev environment. CTRL-C to quit.
localstack    | Starting mock API Gateway (http port 4567)...
localstack    | 2019-12-10T08:07:06:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack    | Starting mock CloudFormation (http port 4581)...
localstack    | Starting mock DynamoDB (http port 4569)...
localstack    | Starting mock IAM (http port 4593)...
localstack    | Starting mock Kinesis (http port 4568)...
localstack    | Starting mock Lambda service (http port 4574)...
localstack    | Starting mock CloudWatch Logs (http port 4586)...
localstack    | Starting mock S3 (http port 4572)...
localstack    | Starting mock SNS (http port 4575)...
localstack    | Starting mock STS (http port 4592)...
localstack    | 2019-12-10 08:07:07,035:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,035:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,035:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,035:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,035:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,035:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,085:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,085:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
localstack    | 2019-12-10 08:07:07,085:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
localstack    | Waiting for all LocalStack services to be ready
localstack    | Listening at http://:::4565
localstack    | Initializing DynamoDB Local with the following configuration:
localstack    | Port:   4564
localstack    | InMemory:       false
localstack    | DbPath: /tmp/localstack/data/dynamodb
localstack    | SharedDb:       true
localstack    | shouldDelayTransientStatuses:   false
localstack    | CorsParams:     *
localstack    | 
localstack    | 2019-12-10 08:07:12,601:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "GET / HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,617:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-2z36qljexnpv HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,626:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-8n3t25w37a1e HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,634:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-sn3afro2r9tz HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,643:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-cxbicls3wsno HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,651:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-manjno7od7om HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,659:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-63x6v8nbah14 HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,667:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-2g2c7o9ebwxb HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,675:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-kinesis-dev-serverlessdeploymentbucket-8ah9wcak0jaa HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,683:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-sls-apis-dev-serverlessdeploymentbucket-gw1fwz2adsfk HTTP/1.1" 200 -
localstack    | 2019-12-10 08:07:12,692:API: 127.0.0.1 - - [10/Dec/2019 08:07:12] "PUT /analytics-sls-apis-dev-serverlessdeploymentbucket-kos9v49a8a5y HTTP/1.1" 200 -
localstack    | Ready.
localstack    | 2019-12-10T08:07:12:INFO:localstack.utils.persistence: Restored 10 API calls from persistent file: /tmp/localstack/data/s3_api_calls.json
localstack    | 2019-12-10 08:08:32,124:API: 127.0.0.1 - - [10/Dec/2019 08:08:32] "GET /analytics-sls-apis-dev-serverlessdeploymentbucket-y192p6ynaelz?location HTTP/1.1" 404 -
localstack    | 2019-12-10 08:08:32,134:API: 127.0.0.1 - - [10/Dec/2019 08:08:32] "HEAD /analytics-sls-apis-dev-serverlessdeploymentbucket-y192p6ynaelz HTTP/1.1" 404 -
localstack    | 2019-12-10 08:08:32,150:API: 127.0.0.1 - - [10/Dec/2019 08:08:32] "PUT /analytics-sls-apis-dev-serverlessdeploymentbucket-y192p6ynaelz HTTP/1.1" 200 -
localstack    | 2019-12-10T08:08:32:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id analytics-sls-apis-dev does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack    | 2019-12-10T08:08:32:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource analytics-sls-apis-dev/ServerlessDeploymentBucket: None
localstack    | 2019-12-10T08:08:32:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'analytics-sls-apis-dev-ServerlessDeploymentBucket-Y192P6YNAELZ'}}
localstack    | 2019-12-10T08:08:32:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "S3::Bucket" id "ServerlessDeploymentBucket"
localstack    | 2019-12-10T08:08:32:DEBUG:localstack.utils.cloudformation.template_deployer: Request for creating resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'analytics-sls-apis-dev-ServerlessDeploymentBucket-Y192P6YNAELZ', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'us-east-1'}}
localstack    | 2019-12-10T08:08:32:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource analytics-sls-apis-dev/ServerlessDeploymentBucketPolicy: None
localstack    | 2019-12-10T08:08:32:WARNING:moto: No Moto CloudFormation support for AWS::S3::BucketPolicy
localstack    | 2019-12-10T08:08:37:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Unable to find stack "analytics-sls-apis-dev" in region us-east-1</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack    | 2019-12-10T08:08:37:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackEvents operation: Unable to find stack "analytics-sls-apis-dev" in region us-east-1 Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 242, in forward
localstack    |     path=path, data=data, headers=forward_headers)
localstack    |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 149, in forward_request
localstack    |     tmp = client.describe_stack_events(StackName=stack_name)['StackEvents'][:1]
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 272, in _api_call
localstack    |     return self._make_api_call(operation_name, kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 576, in _make_api_call
localstack    |     raise error_class(parsed_response, operation_name)
localstack    | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStackEvents operation: Unable to find stack "analytics-sls-apis-dev" in region us-east-1
localstack    | 
localstack    | 
```

**Comment by RichieMerchant** [comment]
I'm also experiencing a very similar issue. 

serverless.yml:
```
version: '3.6'
services:
  ...
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEFAULT_REGION=${DEFAULT_REGION- }
      - AWS_XRAY_SDK_ENABLED=true
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Serverless logs:
```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command deploy
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4569
Serverless: Reconfiguring service kinesis to use http://localhost:4568
Serverless: Reconfiguring service route53 to use http://localhost:4580
Serverless: Reconfiguring service firehose to use http://localhost:4573
Serverless: Reconfiguring service stepfunctions to use http://localhost:4585
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service sts to use http://localhost:4592
Serverless: Reconfiguring service iam to use http://localhost:4593
Serverless: Reconfiguring service ssm to use http://localhost:4583
Serverless: Reconfiguring service rds to use http://localhost:4594
Serverless: Reconfiguring service ec2 to use http://localhost:4597
Serverless: Reconfiguring service elasticache to use http://localhost:4598
Serverless: Reconfiguring service kms to use http://localhost:4599
Serverless: Reconfiguring service secretsmanager to use http://localhost:4584
Serverless: Reconfiguring service logs to use http://localhost:4586
Serverless: Reconfiguring service cloudwatchlogs to use http://localhost:4586
Serverless: Reconfiguring service iot to use http://localhost:4589
Serverless: Reconfiguring service cognito-idp to use http://localhost:4590
Serverless: Reconfiguring service cognito-identity to use http://localhost:4591
Serverless: Reconfiguring service ecs to use http://localhost:4601
Serverless: Reconfiguring service eks to use http://localhost:4602
Serverless: Reconfiguring service xray to use http://localhost:4603
Serverless: Reconfiguring service appsync to use http://localhost:4605
Serverless: Reconfiguring service cloudfront to use http://localhost:4606
Serverless: Reconfiguring service athena to use http://localhost:4607
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: local
Serverless: config.stage: local
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.057s 0 retries] describeStacks({ StackName: 'cbr-api-gateway-local' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.975s 0 retries] createStack({ StackName: 'cbr-api-gateway-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody:
   '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.044s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:000000000000:stack/cbr-api-gateway-local/0a7c6d4e-d8bc-4b5c-b315-3f576452ce2e' })
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - cbr-api-gateway-local
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.024s 0 retries] describeStackResource({ StackName: 'cbr-api-gateway-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.029s 0 retries] listObjectsV2({ Bucket:
   'cbr-api-gateway-local-ServerlessDeploymentBucket-UAKEDO1G86X5',
  Prefix: 'serverless/cbr-api-gateway/local' })
Serverless: [AWS sts undefined 0.287s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:4592), sleeping for ~6 seconds. Try 1 of 4
Serverless: [AWS sts undefined 0.551s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:4592), sleeping for ~5 seconds. Try 2 of 4
Serverless: [AWS sts undefined 0.463s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:4592), sleeping for ~4 seconds. Try 3 of 4
Serverless: [AWS sts undefined 0.331s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (connect ECONNREFUSED 127.0.0.1:4592), sleeping for ~6 seconds. Try 4 of 4
Serverless: [AWS sts undefined 0.357s 3 retries] getCallerIdentity({})

  Serverless Error ---------------------------------------

  ServerlessError: connect ECONNREFUSED 127.0.0.1:4592
      at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:326:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.15.3
     Framework Version:         1.60.0
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

docker-compose logs:
```
localstack_1      | Waiting for all LocalStack services to be ready
localstack_1      | 2019-12-20 16:34:09,801 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1      | 2019-12-20 16:34:09,822 INFO supervisord started with pid 13
localstack_1      | 2019-12-20 16:34:10,831 INFO spawned: 'dashboard' with pid 19
localstack_1      | 2019-12-20 16:34:10,838 INFO spawned: 'infra' with pid 20
localstack_1      | 2019-12-20 16:34:10,847 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1      | (. .venv/bin/activate; bin/localstack web)
localstack_1      | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1      | 2019-12-20 16:34:11,853 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1      | Starting local dev environment. CTRL-C to quit.
localstack_1      | Waiting for all LocalStack services to be ready
localstack_1      | 2019-12-20T16:34:15:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
localstack_1      | Starting mock API Gateway (http port 4567)...
localstack_1      | 2019-12-20T16:34:18:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_1      | Starting mock CloudFormation (http port 4581)...
localstack_1      | Starting mock S3 (http port 4572)...
localstack_1      | Starting mock STS (http port 4592)...
localstack_1      | Waiting for all LocalStack services to be ready
localstack_1      | Ready.
localstack_1      | 2019-12-20T16:38:36:WARNING:moto: No Moto CloudFormation support for AWS::S3::BucketPolicy
```

**Comment by whummer** [comment]
Thanks for reporting @koper89 . A few improvements for Serverless have been pushed recently - can you please check whether the problem persists in the latest version (after a `docker pull localstack/localstack`)? Thanks

@RichieMerchant your problem seems to be different - looks like the STS service is not started. Please add `sts` or `serverless` to the list of `SERVICES`... Thanks

**Comment by nasat75** [comment]
me too, I got the same error message n type

#### summary
- it's success that below below functions 
  - sendOsaka
  - sendDev
- but, a rest of function, `sendTokyo` can't invoked...

#### this is my error console

```
$ sls invoke -f sendTokyo -p ./button-dummy.json --log --aws-profile tambourine-domestic
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - WEBHOOK_OSAKA
Serverless: 	 - WEBHOOK_TOKYO
Serverless: 	 - WEBHOOK_DEV
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: connect ECONNREFUSED 127.0.0.1:80",
    "trace": [
        "Runtime.UnhandledPromiseRejection: Error: connect ECONNREFUSED 127.0.0.1:80",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:210:5)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:485:21)",
        "    at processPromiseRejections (internal/process/promises.js:201:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:32)"
    ]
}
--------------------------------------------------------------------
START RequestId: 347d622c-2f48-4164-94a9-2e4d4c9a761a Version: $LATEST
2020-01-29 19:30:13.817 (+09:00)	347d622c-2f48-4164-94a9-2e4d4c9a761a	INFO	{ text: 'コーヒー淹れたよ' }2020-01-29T10:30:13.818Z
REPORT RequestId: 347d622c-2f48-4164-94a9-2e4d4c9a761a	Duration: 75.74 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 28 MB

Unknown application error occurred



  Error --------------------------------------------------

  Invoked function failed

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           12.3.1
     Serverless Version:     1.21.1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Here's serverless config:


```
service:
  name: notify-coffee
# app and org for use with dashboard.serverless.com
app: notify-coffee
org: nasat75

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  region: ap-northeast-1

functions:
  sendOsaka:
    handler: notify.handle
    environment:
      WEBHOOK_URL: ${env:WEBHOOK_OSAKA}
    events:
      - http:
          path: /osaka
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
  sendTokyo:
    handler: notify.handle
    environment:
      WEBHOOK_URL: ${env:WEBHOOK_TOKYO}
    events:
      - http:
          path: /tokyo
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
```
