### ISSUE TITLE
Cloudwatch event schedule not working.

### ISSUE THREAD

**Issue by AtithAlur** [localstack/serverless-localstack#61]
I am trying to create a ruby lambda and linking it to an event schedule which is set to trigger every minute.
Lambda is working properly. I am able to deploy and invoke as expected.
But, the event rule is not created.
I tried the same serverless configuration on AWS without localstack, it works.
Please help me to resolve this

serverless.yml:

```
service: reminders

provider:
  name: aws
  runtime: ruby2.5

plugins:
  - serverless-localstack
  - serverless-ruby-package

custom:
  rubyPackage:
    alwaysCrossCompileExtensions: true
  localstack:
    stages:
      - dev
    host: http://serverless-localstack
    lambda:
      mountCode: False

package:
  excludeDevDependencies: false
  include:
    - lib/**

functions:
  confirmSchoolReminder:
    handler: lib/confirm_school_reminder.ConfirmSchoolReminder.perform
    events:
      - schedule: rate(1 minute)
```

sls deploy --stage dev:
![](https://user-images.githubusercontent.com/7749613/71051966-923e3d80-210f-11ea-9a85-028bbb701622.png)

sls invoke local -f confirmSchoolReminder:
![](https://user-images.githubusercontent.com/7749613/71052034-cdd90780-210f-11ea-823a-d14c06517d96.png)

ws events list-rules --endpoint http://serverless-localstack:4587 --region us-east-1:
![](https://user-images.githubusercontent.com/7749613/71052088-fc56e280-210f-11ea-81d5-abda18162782.png)

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-41) by [Unito](https://www.unito.io/learn-more)
