### ISSUE TITLE
Is this plugin supposed to work on the latest Serverless version?

### ISSUE THREAD

**Issue by rdsedmundo** [localstack/serverless-localstack#80]
I downloaded the `localstack` and this plugin to give it a try, tried to make it work for 2h, but it simply won't work. A lot of random errors keep happening. The health check is showing that all services are running perfectly, so I either assume that there's an incompatibility with the latest `serverless` framework version, or the README instructions are insufficient.

My config:
```yml
service: serverless-blank

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    # tried with and without the following enabled
    # lambda:
    #   mountCode: true

functions:
  hello:
    handler: src/handler.hello
```

I tried to set up both with an ongoing project and one built from scratch (the Hello World template above), none worked.

Below there are some errors I faced, some of them were because I was using `custom.localstack.lambda.mountCode`, so I disabled it, but then another ones appeared, e.g bucket doesn't exist, so I tried to create the buckets manually using the `awslocal` CLI, but then it threw an error saying that the function already existed during the deployment—I also tried got riding of everything and creating the stack and the service once again, but in the first deployment it already throws that the function already exists.

```
20-03-10T12:05:31:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (404) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>NoSuchBucket</Code>\n    <Message>The specified bucket does not exist</Message>\n    <BucketName>todo-local-ServerlessDeploymentBucket-VXACEBLRD0M8</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```
```
moto.awslambda.exceptions.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the None operation: Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist

<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>__local__</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

```
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: serverless-blank-local-graphql
```

```
  Serverless Error ---------------------------------------

  ServerlessError: The specified bucket does not exist
      at /Users/rdsedmundo/serverless-blank/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:329:27
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by yannbr** [comment]
I got this issue as well, but after waiting ~1min after booting up localstack, the deployment passed that error. (I'm actually stuck on another error)

**Comment by whummer** [comment]
Thanks for reporting @rdsedmundo . We've recently made some improvements to the CloudFormation API - can you please do a `docker pull localstack/localstack` and give it a try with the latest version? Thanks

**Comment by larrybolt** [comment]
Same issues is still happening, I'm using this serverless.yml:
```yml
service: simple-lambda-test
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-localstack
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  logRetentionInDays: 3
  stage: dev
  versionFunctions: false
  environment:
    ENV_VAR_INSIDE_LAMBDA: ${self:custom.envVar}
package:
  exclude:
    - node_modules/**

functions:
  hello:
    handler: hello.handler
    events:
      - http: GET /
          
custom:
  envVar: ${env:ENV_VAR_WHEN_RUNNING_SLS,"default-value"}
  localstack:
    stages: 
      - local
    host: http://nuc
  serverless-offline:
    port: 4000
```
Log I get from localstack is:
```
localstack_main | 2020-03-28T00:43:46:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id simple-lambda-test-local does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-03-28T00:43:46:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource simple-lambda-test-local/ServerlessDeploymentBucket: None
localstack_main | 2020-03-28T00:43:46:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ServerlessDeploymentBucket": 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main | <Error>
localstack_main |     <Code>InvalidBucketName</Code>
localstack_main |     <Message>The specified bucket is not valid.</Message>
localstack_main |     
localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </Error> Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 175, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 243, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 228, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 343, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 84, in Bucket_create_from_cloudformation_json
localstack_main |     result = create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1096, in create_from_cloudformation_json
localstack_main |     bucket = s3_backend.create_bucket(resource_name, region_name)
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 96, in create_bucket
localstack_main |     return create_bucket_orig(bucket_name, region_name, *args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1189, in create_bucket
localstack_main |     raise InvalidBucketName()
localstack_main | moto.s3.exceptions.InvalidBucketName: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main | <Error>
localstack_main |     <Code>InvalidBucketName</Code>
localstack_main |     <Message>The specified bucket is not valid.</Message>
localstack_main |     
localstack_main |     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </Error>
localstack_main | 
localstack_main | 2020-03-28T00:43:46:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateStack" (400) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>InvalidBucketName</Code>\n    <Message>The specified bucket is not valid.</Message>\n    \n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```
And here are the cf stacks: 
https://gist.github.com/larrybolt/5b8ad2644e1d04c34b02f848c3c88572

And here's a demo repo you can try yourself:
https://github.com/catsies-dev/serverless-apigateway-typescript-lambda
