### ISSUE TITLE
Unknown 500 error

### ISSUE THREAD

**Issue by RaeesBhatti** [localstack/serverless-localstack#89]
Here is my `serverless.yml` (the relevant part):
```yaml
custom:
  localstack:
    debug: true
    stages:
      # list of stages for which the plugin should be enabled
      - local
    autostart: true  # optional - start LocalStack in Docker on Serverless deploy
    lambda:
      mountCode: false
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: false

plugins:
  - serverless-localstack
```
Here is the error when I try `sls deploy -s local`:
```
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 4 of 4
 
  Serverless Error ---------------------------------------
 
  500
```
I tried it with `DEBUG=*` as well but it didn't provide any additional information. Here is my env information:
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.20.1
     Framework Version:         1.55.1
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

**Comment by linuxdropout** [comment]
Adding
```
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
```

Fixed this error for me
