### ISSUE TITLE
variables in profile name breaks sls logs

### ISSUE THREAD

**Issue by yonahforst** [localstack/serverless-localstack#90]
I'm getting some strange behavior when i have serverless variables in my profile name, like this:

```yml
custom:
  defaultStage: local
  stage: ${opt:stage, self:custom.defaultStage}
  localstack:
    stages:
      - local
    lambda:
      mountCode: True

provider:
  profile: ${self:custom.stage}Profile
  ....
```

Depending on the command and the parameters, I'll sometimes get `Error: Profile ${self:custom.stage}Profile does not exist`

* `sls deploy` works perfectly.
* `sls deploy -s local` throws the error 
* `sls print` works perfectly.
* `sls print -s local` throws the error 

`sls logs` works differently.  if i call it without the stage variable, it tries to call the real aws endpoint

* `sls logs -f myFunc` throws `The security token included in the request is invalid.`.
* `sls print -s local` throws the profile error

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-33) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @yonahforst . This should be fixed in a7189808717cff31aae3f8252167e1375d79d432 - can you please give it another try with the latest version `0.4.26`? Please report here if the problem persists. Thanks

**Comment by yonahforst** [comment]
@whummer  i think this fix causes the aws endpoints to never be reconfigured. 

I get errors saying that the stack/log-group doesn't exist. I assume that's because the endpoints weren't reconfigured and sls is still trying to talk to the real aws endpoint

**Comment by whummer** [comment]
Thanks for the update @yonahforst . Haven't been able to reproduce this (seems to be working for the examples we tested). Can you please share a small, complete example to reproduce this issue? Thanks!

**Comment by yonahforst** [comment]
sure thing @whummer :)
- add profile called `localProfile` to your ~/.aws/credentials
- run sls to create a new service
- replace the yml file with this:
```yml
service: temp1

custom:
  defaultStage: local
  stage: ${opt:stage, self:custom.defaultStage}
  localstack:
    host: http://${env:LOCALSTACK_HOST, 'localhost'}
    edgePort: ${env:LOCALSTACK_EDGE_PORT, '4566'}
    stages:
      - local

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${self:custom.stage}
  profile: ${self:custom.stage}Profile

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-localstack  
```
- run `sls deploy`
- run `sls info`. You should get `  Stack with id temp1-local does not exist`
- run `sls logs -f hello`. you should get `  The specified log group does not exist.`
